# Generated by Django 5.0.2 on 2024-02-29 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 29, 1, 21, 59, 388157, tzinfo=datetime.timezone.utc), verbose_name='Hora de publicacion'),
        ),
    ]
